### ISSUE TITLE
Even skipping the test with -s option, platform-alteration-service-mesh-usage test is executed if istio is installed

### ISSUE THREAD

**Issue by ramperher** [test-network-function/cnf-certification-test#459]
Hi all!

I have detected a potential issue with `platform-alteration-service-mesh-usage` test in our dallas lab while testing tnf v4.0.2 in our daily jobs. The cluster deployed is OCP 4.7.55 with Verizon WebScale 1.3.5 stack installed, so that Aspenmesh (istio) is running.

In our case, as you know, we are testing your partner pods in our debug jobs, and as we are not configuring service mesh on them, we are always skipping this platform-alteration test.

However, in this [DCI job](https://www.distributed-ci.io/jobs/6a725d48-9977-45e5-85ae-7022cde13f94/tests), you can see the job was executed and, of course, failed, because the pods were not using service mesh (which is expected).

If you see execution.log file [here](https://www.distributed-ci.io/jobs/6a725d48-9977-45e5-85ae-7022cde13f94/files), which is the output of tnf execution, you can see that the test was marked to be skipped with -s argument:

```
-k /var/lib/dci-pipeline/tnf-test-cnf/6a725d48-9977-45e5-85ae-7022cde13f94/inputs/kubeconfig
-i cnf-certification-test:v4.0.2
-t /tmp/ansible.poashszg/cnf-certification-test/cnf-certification-test
-o /tmp/ansible.poashszg/cnf-certification-test/cnf-certification-test
-f operator-install-source operator-install-status-no-privileges operator-install-status-succeeded platform-alteration observability lifecycle networking access-control 
-s platform-alteration-service-mesh-usage 
-s networking-dual-stack-service 
```

In the same link, you can also find the claim.json file generated from this execution.

So, my impression is that there may be something wrong when checking if istio is installed, so that the test is executed in that case, even though it is skipped. Could it be?

**Comment by sebrandon1** [comment]
@jmontesi do you think this has something to do with the #444 PR?  The logs provided sure make it seem like it should be skipping that test but is still sneaking through.

**Comment by ramperher** [comment]
> @jmontesi do you think this has something to do with the #444 PR? The logs provided sure make it seem like it should be skipping that test but is still sneaking through.

Hi Brandon, I think it shouldn't because it's happening in v4.0.2, not in the latest changes from main branch

**Comment by ramperher** [comment]
Oh, I think it has been an error in our side, because we were executing the tnf container specifying `-s` for each skipped tests, instead of doing it once and then list all the tests to be skipped, so that it was only skipping the last one defined. Sorry, it was my fault :sweat_smile: I've already checked it, so nothing to be worried in our side, sorry for the noise.

**Comment by sebrandon1** [comment]
Good to know!
