### ISSUE TITLE
Some tests are linked to a different test suite

### ISSUE THREAD

**Issue by ramperher** [test-network-function/cnf-certification-test#483]
Just raising this issue in case it were a mistake.

By checking a [DCI job](https://www.distributed-ci.io/jobs/e363c7fa-1473-4747-b2df-93bbf9d5ced9/tests) testing the cnf-certification-test main branch, I've seen there are some tests that are not defined within the corresponding test suite, in theory:

- [It] lifecycle manageability-containers-image-tag [extanded, manageability-containers-image-tag] -> should be manageability test suite?
- [It] lifecycle access-control-requests-and-limits [common, access-control-requests-and-limits] -> should be access-control test suite?
- [It] networking access-control-network-policy-deny-all [common, access-control-network-policy-deny-all] -> should be access-control test suite?

**Comment by jmontesi** [comment]
Right. The last one is already fixed after: https://github.com/test-network-function/cnf-certification-test/pull/488

I will prepare a fix for the rest.

**Comment by sebrandon1** [comment]
#491 completed this issue.
