### ISSUE TITLE
When using service-mesh in the pods under test, several tests failed because of istio-proxy container

### ISSUE THREAD

**Issue by ramperher** [test-network-function/cnf-certification-test#505]
Hi all,

With [this change](https://softwarefactory-project.io/r/c/dci-openshift-app-agent/+/26082) in dci-openshift-app-agent, I am testing the inclusion of service-mesh (using Aspenmesh) in the pods under test, in order to execute and validate `platform-alteration-service-mesh-usage test`.

I can confirm the test is working fine and passing. However, there are several tests that now are failing because of the `istio-proxy` container being deployed in the pods under test. These are the following:

- access-control-one-process-per-container
- observability-termination-policy
- networking-undeclared-container-ports-usage
- lifecycle-container-shutdown
- lifecycle-liveness
- lifecycle-pod-scheduling
- lifecycle-statefulset-scaling
- platform-alteration-isredhat-release

[DCI job](https://www.distributed-ci.io/jobs/d17c5dc9-2d8e-445d-b596-596771b725e4/tests) where you can see an example of execution.

Having said that, do you think it is feasible to omit `istio-proxy` container from the tests where containers are check? (because, for example, we can't do anything with lifecycle-statefulset-scaling, I suppose). I mean, while executing these tests, if the container name is `istio-proxy`, just do not execute the tests on that container. What's your opinion on this?

**Comment by sebrandon1** [comment]
@edcdavid Do we just want to filter out any containers that are named `istio-proxy` from the env.Containers in general?

**Comment by ramperher** [comment]
Is there any news regarding this? @sebrandon1 @edcdavid

**Comment by ramperher** [comment]
I'll close this for the moment, if we work again with istio and we continue experiencing issues, I'll let you know
