### ISSUE TITLE
[OCP 4.12] platform-alteration-tainted-node-kernel test is always failing

### ISSUE THREAD

**Issue by ramperher** [test-network-function/cnf-certification-test#566]
Hi all.

Just reporting this here to make you aware of this recurrent issue we have observed in OCP 4.12 daily deployments.

When running the workload that is being tested by tnf in these OCP 4.12 deployments, the test called `platform-alteration-tainted-node-kernel` is currently failing. Here you can see examples:

- https://www.distributed-ci.io/jobs/e9513550-edbe-4036-96e6-981ed2a94641/tests -> complains about cluster6/master-0
- https://www.distributed-ci.io/jobs/a6e267e1-7be8-43e2-8bfa-a6dbdbf272be/tests -> complains about cluster5/master-2

This is the error message offered by tnf:

```
Please note that taints other than 'module was loaded' were found on node master-X.
Taint causing failure: auxiliary taint, defined for and used by distros on node: master-X
```

This is the [command](https://github.com/test-network-function/cnf-certification-test/blob/007110afaed83384ca4cb4e4413a6ae4b89147b7/cnf-certification-test/platform/nodetainted/nodetainted.go#L64) executed on tnf to check the kernel taints present on a node. I could confirm this by running the same command directly in the affected node:

```
[core@master-2 ~]$ cat /proc/sys/kernel/tainted
65536
```

The taint is only appearing in OCP 4.12 deployments, regardless of the cluster where the OCP 4.12 job was executed. It is not affecting to other OCP versions. For example, [this job](https://www.distributed-ci.io/jobs/1fd4b90c-303b-46e9-bf34-89afcda6a007/tests) was executed on cluster6 with OCP 4.10 the same day than the failure in OCP 4.12/cluster6, and you can see that there's no taint registered.

I'm opening this here to discuss with you how we should handle this issue. I believe it's not tnf-related at all, but maybe the kernel behavior in OCP 4.12 is changing. Then, I would like to confirm with you how to escalate this.

**Comment by sebrandon1** [comment]
I've actually never seen `auxiliary taint, defined for and used by distros`, that's a first.  

I was hoping that https://docs.kernel.org/admin-guide/tainted-kernels.html would lend some more information about it in the "detailed" section but no luck.

**Comment by ramperher** [comment]
> I've actually never seen `auxiliary taint, defined for and used by distros`, that's a first.
> 
> I was hoping that https://docs.kernel.org/admin-guide/tainted-kernels.html would lend some more information about it in the "detailed" section but no luck.

It looks like it is a pre-meditated taint, I've been also searching and I've found this: https://unix.stackexchange.com/questions/535084/externally-supported-module-setting-x-kernel-taint-flag, saying that " it's not set by any code in the vanilla kernel".

Do you think it can be a good example to add as a taint that does not trigger the failure on the tnf test? Or to be included somehow in acceptedKernelTaints?

**Comment by sebrandon1** [comment]
`acceptedKernelTaints` should probably be more specific.  That's only for potential 3rd party modules that create kernel tainting, not specifically allowing a kernel taint to pass.

**Comment by ramperher** [comment]
> `acceptedKernelTaints` should probably be more specific. That's only for potential 3rd party modules that create kernel tainting, not specifically allowing a kernel taint to pass.

Okey, I understood this. So, what about to the first proposal? Maybe we can add a condition in `cnf-certification-test` code to pass the test even if this taint is present? Should we validate this with any RH team in charge of kernel taints?

**Comment by ramperher** [comment]
I've finally reported this in this Jira card: https://issues.redhat.com/browse/OCPBUGS-3083, I'll close this.
