### ISSUE TITLE
Node Taints such as "NoSchedule" causes the debug daemonset to not be deployed

### ISSUE THREAD

**Issue by AbhishekBandarupalle** [test-network-function/cnf-certification-test#737]
For OpenShift clusters - where node taints are required for some other applications running on the OpenShift cluster, where the CNF testing is planned - test execution would stop because of the taints.

We need to have another workaround where node taints cannot be removed, so that test execution would not stop.

**Comment by AbhishekBandarupalle** [comment]
Hi,
I wanted to check if we have a workaround for this - I am working with a partner who cannot remove taints on two of their nodes

**Comment by sebrandon1** [comment]
Hello, looking back at the v1.4 Requirements Document:

```
VCP CNF Requirement: CNFS MUST NOT apply tolerations for NoExecute, PreferNoSchedule, and NoSchedule.
```

In my opinion, the partner would be in violation of this requirement by manually cordoning their nodes.  I don't think a workaround will be available for this.

**Comment by mwlinca** [comment]
the best practice guide specifically has a test case for this, but we can provide an exception upon review of test results

**Comment by AbhishekBandarupalle** [comment]
But the taints are applied at the cluster level - not related to CNF. They mentioned that they are sharing the cluster and cannot remove taints. AFAIR, v4.1.2 test suite stopped execution due to the taints. 
Can v4.1.3 run along side the taints and report it as a failure?

**Comment by mwlinca** [comment]
will investigate perhaps an option to support "shared cluster" type deployment execution, by skipping some tests which require test daemonset deployment
