### ISSUE TITLE
Testing of PodDisruptionBudgets makes tnf not working with OCP <= 4.7.x

### ISSUE THREAD

**Issue by ramperher** [test-network-function/cnf-certification-test#749]
I'm opening this issue just to warn you that tnf deployments in OCP versions lower or equal than 4.7 are not working because, when trying to detect the PodDisruptionBudget resources, it fails because this resource is not available for these OCP versions. See example here: https://www.distributed-ci.io/jobs/fdc5b4f2-3c98-45b4-9607-5af707b67c73/files, in execution.log file:

```
[31mFATAL  [0m[Dec 17 12:42:58.508][autodiscover.go: 140] Cannot get pod disruption budgets, error: the server could not find the requested resource 
```

Just saying this because, in the docs: https://test-network-function.github.io/cnf-certification-test/test-spec/#cnf-specific-tests, minimum OCP version is supposed to be 4.6.0. Probably it should be increased to 4.8.0. Also, take into account that 4.7 is EOL.

**Comment by sebrandon1** [comment]
@ramperher is this issue still valid?

**Comment by mwlinca** [comment]
@ramperher doing some clean up - can this be closed or still relevant?

**Comment by ramperher** [comment]
@sebrandon1 @mwlinca As OCP 4.7 is EOL, I think this can be closed, but maybe I'd emphazise this and try to include this comment, because this is still valid: *Just saying this because, in the docs: https://test-network-function.github.io/cnf-certification-test/test-spec/#cnf-specific-tests, minimum OCP version is supposed to be 4.6.0. Probably it should be increased to 4.8.0. Also, take into account that 4.7 is EOL.*

**Comment by sebrandon1** [comment]
Good call, we should probably match up the documentation to what versions of OCP that QE is currently testing against.  Honestly I think the only thing tying us to a certain version of OCP/k8s is the compatibility with the k8s golang client and k8s version.

However, the compatibility matrix on the client-go README [hasn't been updated](https://github.com/kubernetes/client-go/issues/1069#issuecomment-1583000344) in some time so I can't say for certain which features work/don't work with a certain version of k8s/OCP/client-go.
